# Tag API Endpoints

### Variables
@baseUrl = http://localhost:8000/api/v1
@adminAccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0IiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsInR5cGUiOiJhY2Nlc3MiLCJleHAiOjE3NTc0MzQ4MTksImlhdCI6MTc1NzQzMzAxOX0.XejQKtNa6cMtBVFWZm9lhgGtqOWdt_QrMXy0dwAR5tw

## Create a new tag (admin only)

POST {{baseUrl}}/tag
Content-Type: application/json
Authorization: Bearer {{adminAccessToken}}

{
  "name": "golang",
  "description": "Articles related to golang and AI applications",
  "tag_icon": "https://example.com/icon.png",
  "tag_image": "https://example.com/image.png"
}

###

## Get all tags

GET {{baseUrl}}/tag

###

## Get popular tags

GET {{baseUrl}}/tag/popular

###

## Get tag by ID

GET {{baseUrl}}/tag/1

###

## Get tag by slug

GET {{baseUrl}}/tag/slug/golang

###

## Update a tag (full update) (admin only)

PUT {{baseUrl}}/tag/10
Content-Type: application/json
Authorization: Bearer {{adminAccessToken}}

{
  "name": "langchain",
  "description": "Articles related to langchain and AI applications",
  "tag_icon": "https://example.com/icon.png",
  "tag_image": null
}

###

## Partially update a tag (admin only)

PATCH {{baseUrl}}/tag/10
Content-Type: application/json
Authorization: Bearer {{adminAccessToken}}

{
  "tag_image": "https://example.com/image.png"
}

###

## Delete a tag (admin only)

DELETE {{baseUrl}}/tag/10
Authorization: Bearer {{adminAccessToken}}

###
