services:
  db_local_blog_api:
    container_name: db_local_blog_api
    build:
      context: ./dockerDB
      dockerfile: Dockerfile.local
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata_local:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db_dockerDB_blog_api_network

volumes:
  pgdata_local:

networks:
  db_dockerDB_blog_api_network:
    driver: bridge